### ISSUE TITLE
CASA scan succeeded with no Files to be tested

### ISSUE THREAD

**Issue by CloudAktsk** [fluidattacks/makes#1121]
I follow the doc to do my CASA scan
https://docs.fluidattacks.com/tech/scanner/standalone/casa/

I run the following command:
`docker run -v /Users/cloudlin/Downloads/repo:/working-dir ghcr.io/fluidattacks/makes/arm64 m gitlab:fluidattacks/universe@trunk /skims scan ./fluid-config.yaml`
It returned success but no file has been tested, log:
```
─────────────────────────────────── Running ────────────────────────────────────

[INFO] Official Documentation: https://docs.fluidattacks.com/machine/scanner/standalone/
[INFO] Namespace: OWASP
[INFO] info HEAD is now at: 7763729d6fcd5bb649c7e03c2fadfea31d9b6d59
[INFO] Startup work dir is: /working-dir
[INFO] Moving work dir to: /working-dir
[INFO] Files to be tested: 0
[INFO] Files to be tested: 0
[INFO] An output file has been written: /working-dir/Fluid-Attacks-Results.csv
[INFO] Summary: No vulnerabilities were found in your targets.

───────────────────────────────── 🧜 Success! ──────────────────────────────────
```
I'm pretty sure I have some source code in my repo in Java (Android Studio project) and APK.
But why the scanner didn't test any script?

Here is my `config.yaml`
```
namespace: OWASP
output:
  file_path: ./Fluid-Attacks-Results.csv
  format: CSV
working_dir: .
sast:
  include:
    - /Users/cloudlin/Downloads/repo
    - /Users/cloudlin/Downloads/repo/unityLibrary/src/main/java/com/unity3d/player/UnityPlayerActivity.java
sca:
  include:
    - /Users/cloudlin/Downloads/repo
apk:
  include:
    - /Users/cloudlin/Downloads/repo/universal.apk

checks:
- F001
- F004
- F008
- F009
- F010
- F011
- F012
- F015
- F016
- F017
- F020
- F021
- F022
- F023
- F031
- F034
- F035
- F037
- F042
- F043
- F052
- F055
- F056
- F058
- F073
- F075
- F079
- F080
- F082
- F085
- F086
- F089
- F091
- F092
- F094
- F096
- F098
- F099
- F100
- F103
- F107
- F112
- F120
- F127
- F128
- F129
- F130
- F131
- F132
- F133
- F134
- F143
- F160
- F176
- F177
- F182
- F200
- F203
- F206
- F207
- F211
- F234
- F239
- F246
- F247
- F250
- F252
- F256
- F257
- F258
- F259
- F266
- F267
- F268
- F277
- F281
- F300
- F313
- F320
- F325
- F333
- F335
- F338
- F346
- F363
- F372
- F380
- F381
- F393
- F394
- F396
- F398
- F400
- F401
- F402
- F406
- F407
- F408
- F409
- F411
- F412
- F413
- F414
- F416
- F418
language: EN
```

**Comment by jgomezb11** [comment]
Hello,
I see you have a small error when defining the scan paths in the config.yaml. 

To give you a bit of context, when you run `docker -v <local/path>:<container/path>` you are making a copy of your local folder inside the container's runtime. Keeping in mind that the scan runs inside the container, the paths you are declaring in the config.yaml should not be from your local folder but from the copy you made inside the container.

For that reason, if you want to scan `/Users/cloudlin/Downloads/repo`, you should put in the include the `.` (which is really the path to the copy of your folder in the container's runtime thanks to the `docker run -v /Users/cloudlin/Downloads/repo:/working-dir`), as specified in the documentation.

That's on one hand, on the other, it's not necessary for you to define the second include in sast ('/Users/cloudlin/Downloads/repo/unityLibrary/src/main/java/com/unity3d/player/UnityPlayerActivity.java') since when you try to scan a folder the scanner will recursively go through all the files inside it.

Finally, it's worth highlighting that if you want to target a specific file as in the case of `universal.apk`, you can do it as long as the path is relative to the folder that exists in the container's runtime, in this case you could replace `/Users/cloudlin/Downloads/repo/universal.apk` by `./universal.apk`. 

I hope I've helped you, if you have any other questions don't hesitate to respond to this issue.

**Comment by CloudAktsk** [comment]
Hello @jgomezb11,
thank you for your detailed explanation. 

I have no experience with using Docker, so I made this stupid mistake. 
After adopting your solution, I was able to successfully scan the file. 😄 

Thank you again for your help!
