### ISSUE TITLE
Keep the path of the file without /nix/store

### ISSUE THREAD

**Issue by ludsrill** [fluidattacks/makes#332]
Is it possible keep in a var, the path of the file that is being compiled, linted, etc, without the /nix/store/21dcs... part, to be able to add it in the builder.sh as debug info

I found that when I do nested derivation the path that is given for the CLI is something like this

`/nix/store/sbfy5d81gnx6hnhiczms5019vzm1hd2l-build-lint-clojure-for-clojure--nix-store-jfa5l9j0hqy8wg6a7gjgwa83nncs5f2v-slayfer1112.clj.drv`

Where I completely lost the path of the file and I only get the basename

**Comment by dsalaza4** [comment]
Nix derivations are built in a clean directory stored in `/tmp`, the purpose of this is not allowing global state usage, like repository files. In order to be able to use files within `makeDerivation`, you need to pass them via Nix, which will move them to `/nix/store`. `makeEntrypoint` allows you to directly reference files within the repo without passing them via Nix, but it does not cache.

**Comment by ludsrill** [comment]
this solution can work perfectly for me, however, my problem has its origin in this test https://github.com/fluidattacks/makes/pull/331/commits/9af96b30da2ea47c5ba64355561ebf5fc1c19182 

Although I am using your approach, at some point I'm losing the path to the file, I think the problem is here: https://github.com/fluidattacks/makes/pull/331/commits/9af96b30da2ea47c5ba64355561ebf5fc1c19182#diff-d5c545b330bdc5ae342a7654ef37900bc06689391181087debe8f257e8cc12c4R15

**Comment by ludsrill** [comment]
I just confirmed if I do this  
`targets = builtins.map projectPath targets;` 

I will get this :
`/nix/store/sbfy5d81gnx6hnhiczms5019vzm1hd2l-build-lint-clojure-for-clojure--nix-store-jfa5l9j0hqy8wg6a7gjgwa83nncs5f2v-slayfer1112.clj.drv`

instead of this:
`/nix/store/w0y73hi442xgm3an162hds67g8asnak9-build-lint-clojure-for--code-codeabbey-038-slayfer1112.clj.drv`

**Comment by kamadorueda** [comment]
What you can do is in src/args/lint-clojure, at makeTarget, pass two arguments,
the nix-store path to lint, and the relative path as the user specify it in makes.nix

you use the relative path to name the derivation, and the nix-store path to run the linter over it

**Comment by kamadorueda** [comment]
there is also other thing you can use to turn /nix/store/123-name-version into something meaningful: 

```
builtins.parseDrvName "/nix/store/121g7srkk3il0x0vbc5x39r4d0az5s4x-p7zip-17.04"     
{ name = "/nix/store/121g7srkk3il0x0vbc5x39r4d0az5s4x-p7zip"; version = "17.04"; }
```

**Comment by kamadorueda** [comment]
You can also remove the prefix `builtins.storeDir` and the hash

**Comment by ludsrill** [comment]
> What you can do is in src/args/lint-clojure, at makeTarget, pass two arguments,
> the nix-store path to lint, and the relative path as the user specify it in makes.nix
> 
> you use the relative path to name the derivation, and the nix-store path to run the linter over it

I'm going to use this approach

There is a special reason to avoid pass the relative path as the user specify to **src/args/lint-clojure** directly and then make `envTarget = projectPath target` ?

**Comment by kamadorueda** [comment]
> There is a special reason to avoid pass the relative path as the user specify to **src/args/lint-clojure** directly and then make `envTarget = projectPath target` ?

API consistency

All other args work like this, so either:
- we migrate all other args to work this way
- we avoid doing it this way

Initially I decided to work over nix-store-paths over relative-paths-as-string because nix-store paths are not project-dependent, which offer more flexibility, which is what you look for when extending makes. I'm not sure if I want to drop that for comestic reasons right now, but I'm open to see patterns emerge over time and adapt to them
