### ISSUE TITLE
eval caching implications of not using flakes under the hood?

### ISSUE THREAD

**Issue by blaggacao** [fluidattacks/makes#509]
I wonder what the implications of using 
https://github.com/fluidattacks/makes/blob/939a40963d820ad35a296d00cabe43cdce16eae7/src/cli/main/__main__.py#L128-L144

are for eval caching?

See also elco's blog post about flakes, especially the last few paragraphs:

https://www.tweag.io/blog/2020-06-25-eval-cache/

**Comment by kamadorueda** [comment]
I decided not to implement flakes simply because they are an **unstable** feature of Nix.
This means that when flakes get to be stable (which may be soon https://discourse.nixos.org/t/nix-release-schedule-and-roadmap/14204) **we'll** support it and use it instead of this `nix-build` that you mention

Now, as per the evaluation caching, I can not answer from a theoretical point of view, but I can tell you that we've not experienced performance degradations for not using flakes so far in our real life project (https://gitlab.com/fluidattacks/product), so I'm pretty sure real life users won't experience them either

From what I see, Makes is leveraging the current **stable** state of the art that Nix offers, as Nix offers it, so we won't change that for the moment. 
However, I'm excited to see Flakes become stable and then upstream those benefits into Makes!
