### ISSUE TITLE
`numtide/treefmt`

### ISSUE THREAD

**Issue by blaggacao** [fluidattacks/makes#586]
zimbatm has finally gotten around to do https://github.com/numtide/treefmt

This is a standardized code formatter that should work uniformly and in parallel around many code formatters out there and work smoothly (enough) with editors, written in rust.

I think `makes` would benefit a great deal embracing this project, because of rust-like concurrency, but most of all, because of easy editor integration, rust-speed file walker (`bash` & `nix` afaik are slow) and a reasonably simple configuration format.

**Comment by kamadorueda** [comment]
we currently run each linter/formatter on a different job, on a different machine on CI, 

![image](https://user-images.githubusercontent.com/47480384/134037744-9e404f38-7ed8-46d7-bb42-ad2b8667289e.png)

this have some benefits:
- it's faster, because each machine runs 1 piece of the N linters and machines work in parallel. This is faster than 1 machine running the N linters alone
- cache is done separately, so if I modify only python code, only python linters run, therefore most linters/formatters are a no-op the majority of the time (just downloading an empty file from the cache) like this: 
![image](https://user-images.githubusercontent.com/47480384/134038098-5bda70e4-bf94-435f-bca7-f246fa2445a6.png)
- this increases developer productivity as they have to wait less for the pipeline to complete, therefore saving dev time ($$$) && increasing time2market

and some trade-offs:
- you use more machine time in total, so more aws bill $$$
- with treefmt we would have 1 command locally instead of N as today, that's nice

---

for the last part, I don't remember the last time I had to run a formatter locally, it's embedded in my editor: https://github.com/kamadorueda/machine/blob/main/src/config/system/userActivationScripts/vscode/default.nix#L26
linters are there too

**Comment by kamadorueda** [comment]
just to clarify, I'm not saying not 😁 
we are open to community contributions for this

**Comment by blaggacao** [comment]
I'm predicting to hit this again somewhere around the next two weeks for more thorough design considerations :smile:

**Comment by dsalaza4** [comment]
As discussed in #502, we will no longer maintain builtins for specific tools. Developers will be able to import such tools to makes and used them accordingly.
