### ISSUE TITLE
Support creating random self-signed SSL certificates for development purposes

### ISSUE THREAD

**Issue by kamadorueda** [fluidattacks/makes#642]
We have this utility: https://gitlab.com/fluidattacks/product/-/tree/3e81d4681fde4912cc36dfe25cc16f64f7675d7f/makes/utils/ssl-certs
that we use for adding SSL certs to local versions of web servers. It would be nice to have it embedded on Makes

**Comment by blaggacao** [comment]
https://github.com/FiloSottile/mkcert look no further IMHO :smile:

**Comment by jpverde** [comment]
Done at #773

**Comment by blaggacao** [comment]
I'm not sure if this has been overlooked but `mkcert` also knows how to (temporarily!) import self signed certs into the relevant syst paths so that the browser, for example, would accept them as valid certs and not show the annoying unknown cert screen + other benefits.

But maybe the main use case here is for generating production root CA.

I just wondered. :smile:

**Comment by jpverde** [comment]
@blaggacao hmm, we can give `mkcert` a try for our specific use case. In the meantime, we can give this a separate issue to keep this on track, since the main issue here was to embed a utility we're using right now.

**Comment by blaggacao** [comment]
no worries, I just had the feeling the true greatness of `mkcert` somehow slipped :smile:
