### ISSUE TITLE
Use skim/fzf for fuzzy finding jobs

### ISSUE THREAD

**Issue by nrdxp** [fluidattacks/makes#771]
The new TUI is pretty awesome, but the native python implementation to complete and find jobs could do with some improvement. Rather than reinventing the wheel here, it may be better simply to call out to a program that already does this quickly and efficiently. [Fzf](https://github.com/junegunn/fzf) and [Skim](https://github.com/lotabout/skim) are two fantastic options, and their APIs are almost completely interchangable, so we could actually use either or and leave it up to the user if desired.

**Comment by jpverde** [comment]
This seems pretty nice. Currently, we're trying to improve the TUI, and these two libs look great.

**Comment by dsalaza4** [comment]
Hopefully we will soon start working on #989. 

We're considering getting rid of `main.nix` files and rather have everything described in `makes.nix` files, which are imported via `imports = []` like in nixos. That way we won't have to spend CLI init time searching for files within the repo, which gets especially painful in monorepos

**Comment by Ten0** [comment]
Since this is marked as completed, should I understand that the new Makes CLI enables fuzzy matching with fzf (or similar) when looking for jobs instead of the previous "one-letter-longest match" mode ?
(That would be a great improvement indeed because I type much faster than the time it would take me to check what it auto-completed to figure out what the next letter should be.) 
(I don't see it in the README screenshot, is that just meant to be updated later?)
Thanks! 😊

**Comment by dsalaza4** [comment]
The CLI currently does not support fuzzy matching. Once we start working on #989 such feature will most likely be implemented. This issue was closed in favor of #989
