### ISSUE TITLE
Makes initialization is taking forever when using a slow internet connection

### ISSUE THREAD

**Issue by dsalaza4** [fluidattacks/makes#826]
When I'm in a hotel or an airport and run:

```bash
m . /<job>
```

or:

```bash
m .
```

it takes makes a VERY long time to actually execute the job or open the CLI with available jobs.
The last thing I see in the logs is the `Building project configuration` message.

This goes beyond cache as it always happens, no matter if I already ran it multiple times on the machine.

**Comment by dsalaza4** [comment]
This has been getting worse lately, Since yesterday, jobs are taking several minutes to start executing even on good internet connections.

**Comment by melg8** [comment]
With all my love to nix, this is now main blocker for me:
 1) long startup even for "choose" screen.
 2) some pipelines are deployed in restricted local networks without even internet connection, this scenario is not supported?

**Comment by jpverde** [comment]
We managed to improve highly the initialization times by updating the nixpkgs channels. Also @melg8 , I don't know if it could be possible to make it run without an internet connection due to the cache system being online, we could discuss if we really need that to be a feature, but for now, it's not a necessity.
