### ISSUE TITLE
Support Bitbucket pipelines & Bamboo

### ISSUE THREAD

**Issue by kamadorueda** [fluidattacks/makes#83]
Based on:
- https://github.com/fluidattacks/makes/issues/26
- https://github.com/fluidattacks/makes/issues/25

Add support for Bitbucket pipelines & Bamboo, it is basically only adding documentation explaining how to set it up and propagating secrets. Container Images are already built

**Comment by dsalaza4** [comment]
@kamadorueda I feel like we're constantly looking at how things work on both Gitlab and Github primarily because we rely on both of them, it wouldn't be the same case with Bitbucket. Should we test this somehow? maybe too complex? Maybe we just need a few contributors who actually use Bitbucket? :thinking:

**Comment by kamadorueda** [comment]
In reality supporthing any CI/CD provider is simple, they all start from some container image and execute some scripts on top of it

I was investigating and all providers we support right now (github, gitlab, travis) do actually define CI=true, so even that is some kind of standard

What I try to say is: it just costs us a few lines in the documentation, and benefits a lot the community that needs it the most (banking, etc), since they use those rare alternatives for X reasons

It also increases a lot the scope of the project, and since almost everything is standard, it has no complexity cost beyond the initial investment on writing some docs
