### ISSUE TITLE
Support private registries in makeNodeJsModules

### ISSUE THREAD

**Issue by dacevedo12** [fluidattacks/makes#834]
Some projects require downloading deps from private registries i.e. https://fontawesome.com/docs/web/setup/packages#alternate-per-project-setup-using-environment-variables

Would be useful to have a way to provide environment secrets so they can be used by npm

**Comment by juansedo** [comment]
### Context

Going deep on `makeNodeJsModules`, the current implementation tries to download each dependency as a nix derivation previously of `npm install` command (for caching, I guess).

It's using `nixpkgs.fetchurl` for downloading packages [[1]](https://github.com/fluidattacks/makes/blob/726a5218739295a71d9543683e5dac8014813860/src/args/make-node-js-modules/default.nix#L25), but it resolves on 401 error for private registries due to `fetchurl` is not handling auth tokens on `.npmrc` such as `npm install` would do:

![image](https://github.com/fluidattacks/makes/assets/52968530/bb4e43ff-41e9-41b0-9c8f-255e7f05e9f4)

### Suggested solution

`collectDependencies` function [[2]](https://github.com/juansedo/makes/blob/726a5218739295a71d9543683e5dac8014813860/src/args/make-node-js-modules/default.nix#L22C1-L30) must be modified to preload `.npmrc` auth tokens for handling the private registries. It sounds like a breaking change and, does anyone know if `fetchurl` would allow that?

There's a slightly related issue [!1043](https://github.com/fluidattacks/makes/issues/1043) about the npm, node, and lockfileVersion problem. Any suggested solution can impact that issue.

**Comment by juansedo** [comment]
@dsalaza4 @jpverde
According to [NixOS wiki](https://nixos.wiki/wiki/Enterprise), there is a way to download private resources using fetchurl:
![image](https://github.com/fluidattacks/makes/assets/52968530/9fd3ac24-9478-4262-af6c-cf63e821c1bb)

What do you think about this solution?
`netrc-file` can be created, but can we modify nix.conf file when makes start?

**Comment by dacevedo12** [comment]
dream2nix ain't gonna cut it either. https://github.com/nix-community/dream2nix/blob/3802b906b4107e2d8bedc292d9c43779c4b4ec47/src/fetchers/npm/default.nix#L50

node2nix however seems closer to it https://github.com/svanderburg/node2nix/issues/172

nixpkgs.fetchUrl supports a `curlOpts` argument that can be used to pass the token, something like
```
__nixpkgs__.fetchurl {
  url ="https://npm.fontawesome.com/@fortawesome/fontawesome-pro/-/6.4.0/fontawesome-pro-6.4.0.tgz";
  hash = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
  curlOptsList = [
    "--header" "Authorization: Bearer TOKEN_GOES_HERE"
  ];
}
```
Can confirm it works.
